
platform :ios, '9.0'

target 'discountcooking' do
  use_frameworks!

  # Pods for discountcooking

  pod 'Alamofire', '~> 4.5'
  
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'FirebaseDatabase'
  pod 'QRCode'
  pod 'QRCodeReader.swift', '~> 8.0.3'
  pod 'NVActivityIndicatorView'
  pod 'Eureka'
  pod 'ImageRow', '~> 3.0'
  target 'discountcookingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'discountcookingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
